name: Contribution Matrix

on:
  schedule:
    - cron: "17 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: leemaxyum
          outputs: |
            output/github-snake-dark.svg

      - name: Commit generated asset
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update contribution matrix"
          add: "output/github-snake-dark.svg"
